# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='message',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='phone',
        ),
    ]
