# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171115_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
